blog/config/routes.rb
Blog::Application.routes.draw do
  get "post/index"
  get "post/new_post"
  post "post/create"

end

blog/app/models/post.rb
class Post < ActiveRecord::Base
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blog/app/controllers/post_controller.rb
class PostController < ApplicationController
  def index
    @posts = Post.all()
  end

  def new_post
  end

  def create
    @post = Post.new(post_params)
    
    @post.save
    redirect_to post_index_path
  end
  
  private
    def post_params
      params.require(:post).permit(:title, :author, :body)
    end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/post_helper.rb
module PostHelper
end

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

blog/app/views/post/create.html.erb
<h1>Post#create</h1>
<p>Find me in app/views/post/create.html.erb</p>

blog/app/views/post/index.html.erb
<h1>Posts</h1>

<% @posts.each do |post| %>
  <%= post.title %><br>
  <%= post.author %><br>
  <%= post.body %><br>
  <%= post.created_at %><br>
<% end %>

blog/app/views/post/new_post.html.erb
<h1>New Post</h1>

<%= form_for :post, url: post_create_path do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>  
    <%= f.label :author %>
    <%= f.text_field :author %>
  </p>
  
  <p>  
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
  
<% end %>