celebrity/config/routes.rb
Celebrity::Application.routes.draw do
  get "people/index"
  get "people/new_name"
  post "people/create"
  get "people/random"
  
  

end

celebrity/app/models/people.rb
class People < ActiveRecord::Base
end

celebrity/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

celebrity/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = People.all()
  end

  def new_name
  end

  def create
    @people = People.new(post_params)
    
    @people.save
    redirect_to people_index_path
  end
  
  def random
    total_people= People.count()
    random_number= rand(0..total_people)
    @person = People.find(random_number)
  end
  
  def clear_list
   
  end
  
  private 
    def post_params
      params.require(:people).permit(:name)
    end
   
end

celebrity/app/helpers/application_helper.rb
module ApplicationHelper
end

celebrity/app/helpers/people_helper.rb
module PeopleHelper
end

celebrity/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Celebrity</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

celebrity/app/views/people/create.html.erb
<h1>People#create</h1>
<p>Find me in app/views/people/create.html.erb</p>

celebrity/app/views/people/index.html.erb
<h1>People</h1>

<% @people.each do |post| %>
  <%= post.name %><br>
  
<% end %>

<%= link_to 'New name', people_new_name_path %>

celebrity/app/views/people/new_name.html.erb
<h1>Add Names</h1>

<%= form_for :people, url: people_create_path do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name, :autocomplete => :off %>
  </p>
  
  <p>
    <%= f.submit 'submit' %>
  </p>
  
  <%= link_to 'Start Playing', people_random_path %>
  
<% end %>

celebrity/app/views/people/random.html.erb
random<br>
<%= @person.name %><br>

<%= link_to 'Next', people_random_path %><br>

<%= link_to 'Add More', people_new_name_path %>